<a href="https://colab.research.google.com/github/Cecilben/7_dof_iiwa/blob/master/June_13__kabsch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
def kabsch_umeyama(A, B):
    """B  is aligned to A"""
    assert A.shape == B.shape
    n, m = A.shape
 
    EA = np.mean(A, axis=0)
    EB = np.mean(B, axis=0)
    VarA = np.mean(np.linalg.norm(A - EA, axis=1) ** 2)
 
    H = ((A - EA).T @ (B - EB)) / n    
    U, D, VT = np.linalg.svd(H)
    # d = np.sign(np.linalg.det(U) * np.linalg.det(VT))
    # S = np.diag([1] * (m - 1) + [d])
    R= U @ VT
    # R = U @ S @ VT
    c=1
    # c = VarA / np.trace(np.diag(D) @ S)
    t = EA - c * R @ EB
 
    return R, c, t
 
    
#Example
#Robot
A = np.array([[800.559, -430.056,   339.981],
              [800.559,430.056, 339.923],
              [800.568,-430.041,    339.984],
              [610.023, -499.991,   340.058],
              [608.381, -498.282,   738.768],
              [800.559, 430.056,    339.98]])
 
 
#Camera
B = np.array([[386.523, -349.12,    2086.989],
              [-450.87, -284.62,    2031.087],
              [387.243, -351.53,    2087.195],
              [444.063, -343.04,    2276.608],
              [436.074,  45.092,    2291.748],
              [-453.0,  -292.26,    2031.054]])


 
 
#Function call:
R, c, t = kabsch_umeyama(B, A)   # Swapped inorder to get the Tsystem inverse
print("Rotation")
print(R)
print("translation")
print(t)
print("scaling")
print(c)

# With this R,c and t we get Tsystem inversed

# transform_cr= np.concatenate((R,t), axis =1)
# scalingMatrix = np.array([[0,0,0,1]])
# transform_cr = np.concatenate((transform_cr,scalingMatrix),axis = 0)
# print(transform_cr)

# def transformation_matrix(R,t):
#     transform_cr= np.concatenate((R,t), axis =1)
#     scalingMatrix = np.array([[0,0,0,1]])
#     transform_cr = np.concatenate((transform_cr,scalingMatrix),axis = 0)
#     print(transform_cr)

# transformation_matrix(R.T,t.T)

Rotation
[[ 0.07211082 -0.99587172  0.05513207]
 [ 0.01753145  0.05653301  0.9982468 ]
 [-0.99724254 -0.07101785  0.02153572]]
translation
[-116.22180132 -671.82705694 2848.28784257]
scaling
1


In [ ]:

def camera_robot_convertor():
    """Aplies R,c and t to B"""
    # B_transformed = np.array([t + c* R @ b for b in B]) 
    B_transformed = np.array([t + R @ b for b in B])   # Without scaling, c
    print(B_transformed)

print("Camera to Robot conversion")
B_trans = camera_robot_convertor()

print("Original robot points",A)


print("Camera points Before transformation")
print(B)
# B after transformed to robot system
B_t= np.array([[ 802.81903472, -435.31749964,  331.52523398],
 [ 799.21944483,  428.58429497,  348.99294409],
 [ 802.61807281, -436.20845064,  329.10087176],
 [ 613.06988952, -507.61287241,  345.20433754],
 [ 603.96450285, -478.02433078,  742.82809572],
 [ 798.95805527,  430.3208585,   341.04251691]])

# Both A and B_t are in Robot coordinate system
rmse = np.linalg.norm(B_t-A) / len(A)
print("RMSE:",rmse)


# if rmse < 1e-5:
#     print("Permissible")
# else:
#     print("Non Permissible ...")

# #TESTING
# # Random rotation and translation
# R = np.random.rand(3,3)
# t = np.random.rand(3,1)
# c=1

# # make R a proper rotation matrix, force orthonormal
# U, S, Vt = np.linalg.svd(R)
# R = U@Vt

# # number of points
# n = 6

# A = np.random.rand(3, n)
# B = R@A + t


# # Recover R and t
# ret_R, ret_t,ret_c = kabsch_umeyama(B,A)

# # Compare the recovered R and t with the original
# B2 = (ret_R@A) + ret_t

# # Find the root mean squared error
# err = B2 - B
# err = err * err
# err = np.sum(err)
# rmse = np.sqrt(err/n)

# print("Points A")
# print(A)
# print("")

# print("Points B")
# print(B)
# print("")

# print("Ground truth rotation")
# print(R)

# print("Recovered rotation")
# print(ret_R)
# print("")

# print("Ground truth translation")
# print(t)
# print("Recovered translation")
# print(ret_t)


# print("RMSE:", rmse)

# if rmse < 1e-5:
#     print("Everything looks good!")
# else:
#     print("Hmm something doesn't look right ...")



Camera to Robot conversion
[[ 3.74389457e+02  1.39854253e+03  2.53256923e+03]
 [ 2.46688640e+02  1.33170420e+03  3.36186861e+03]
 [ 3.76852785e+02  1.39862455e+03  2.53202680e+03]
 [ 3.82937903e+02  1.58918157e+03  2.47883968e+03]
 [-3.33317364e+00  1.62609724e+03  2.45956840e+03]
 [ 2.54141684e+02  1.33120201e+03  3.36453460e+03]]
Original robot points [[ 800.559 -430.056  339.981]
 [ 800.559  430.056  339.923]
 [ 800.568 -430.041  339.984]
 [ 610.023 -499.991  340.058]
 [ 608.381 -498.282  738.768]
 [ 800.559  430.056  339.98 ]]
Camera points Before transformation
[[ 386.523 -349.12  2086.989]
 [-450.87  -284.62  2031.087]
 [ 387.243 -351.53  2087.195]
 [ 444.063 -343.04  2276.608]
 [ 436.074   45.092 2291.748]
 [-453.    -292.26  2031.054]]
RMSE: 4.986605441333441


In [ ]:
## testing a single point 
test_B = np.array([[-120.39,119.114,2384.888],[-236.5,334.4,2345.3]]) ## point in camera
#A = np.array([[745.75,-395.11,655.83]]) ## original point in robot CS

def camera_robot_convertor():
    """Aplies R,c and t to B"""
    B_transformed = np.array([t + c* R @ b for b in test_B])           # b' = t + c*R*b...b= point in camera system and b' = same point in robot coordinate system
    print(B_transformed)

print("Point in Camera system",test_B)
print("")
print("Camera point transformed to robot system, Pc_transformed:")
B_trans = camera_robot_convertor()
print("")

print("Point in robot coordinate system,Pr:",A)
print("")

print("//Due to correspondance assumption between points in camera and robot coordinate system it should follow, Pc_transformed = Pr")




Point in Camera system [[-120.39   119.114 2384.888]
 [-236.5    334.4   2345.3  ]]

Camera point transformed to robot system, Pc_transformed:
[[-112.04166582 1713.50301087 3011.24692848]
 [-336.99426125 1684.11960491 3110.89505393]]

Point in robot coordinate system,Pr: [[ 800.559 -430.056  339.981]
 [ 800.559  430.056  339.923]
 [ 800.568 -430.041  339.984]
 [ 610.023 -499.991  340.058]
 [ 608.381 -498.282  738.768]
 [ 800.559  430.056  339.98 ]]

//Due to correspondance assumption between points in camera and robot coordinate system it should follow, Pc_transformed = Pr


Trobot_in_camera = Tsystem * Tcamera
Output = Input

R and t in robot coordinate is available 

Rotation sequence 
1. Robot: RzRyRx
2. Camera: RxRyRz

Testing

In [ ]:
import numpy as np

def kabsch(A, B):
    assert A.shape == B.shape

    num_rows, num_cols = A.shape
    # if num_rows != 3:
    #     raise Exception(f"matrix A is not 3xN, it is {num_rows}x{num_cols}")

    # num_rows, num_cols = B.shape
    # if num_rows != 3:
    #     raise Exception(f"matrix B is not 3xN, it is {num_rows}x{num_cols}")

    # find mean column wise
    centroid_A = np.mean(A, axis=1)
    centroid_B = np.mean(B, axis=1)

    # ensure centroids are 3x1
    centroid_A = centroid_A.reshape(-1, 1)
    centroid_B = centroid_B.reshape(-1, 1)

    # subtract mean
    Am = A - centroid_A
    Bm = B - centroid_B
   # # Calculate Familiar covariance matrix
    H = Am @ np.transpose(Bm)   # np.matmul(A,B.T)

    # find rotation...Using svd() operator which decomposes H 
    U, S, Vt = np.linalg.svd(H)
    R = Vt.T @ U.T
   #Trnslation
    t = -R @ centroid_A + centroid_B

    return R, t

# import numpy as np
# def kabsch(A, B):
#     """B  is aligned to A"""
#     assert A.shape == B.shape
#     n, m = A.shape
 
#     EA = np.mean(A, axis=0)
#     EB = np.mean(B, axis=0)
#     VarA = np.mean(np.linalg.norm(A - EA, axis=1) ** 2)
 
#     H = ((A - EA).T @ (B - EB)) / n    
#     U, D, VT = np.linalg.svd(H)
#     # d = np.sign(np.linalg.det(U) * np.linalg.det(VT))
#     # S = np.diag([1] * (m - 1) + [d])
#     R= U @ VT
#     # R = U @ S @ VT
#     c=1
#     # c = VarA / np.trace(np.diag(D) @ S)
#     t = EA - c * R @ EB
 
#     return R, t
    
# Test with random data

# Random rotation and translation
R = np.random.rand(3,3)
t = np.random.rand(3,1)

# make R a proper rotation matrix, force orthonormal
U, S, Vt = np.linalg.svd(R)
R = U@Vt

A = np.random.rand(3, 6)  # 6points
B = R@A + t

# Recover R and t
ret_R, ret_t = kabsch(A, B)

# Compare the recovered R and t with the original
B2 = (ret_R@A) + ret_t

# Find the root mean squared error
err = B2 - B
err = err * err
err = np.sum(err)
rmse = np.sqrt(err/6)   # n = 6

print("Points A:")
print(A.T)
print("")

print("Points B")
print(B.T)
print("")

print("Ground truth rotation")
print(R.T)

print("Recovered rotation")
print(ret_R.T)
print("")

print("Ground truth translation")
print(t.T)

print("Recovered translation")
print(ret_t.T)
print("")

print("RMSE:", rmse)



Points A:
[[0.99218711 0.13509565 0.37632505]
 [0.15294858 0.87979034 0.31031327]
 [0.69997235 0.21693705 0.01155667]
 [0.11233495 0.61443301 0.50550907]
 [0.91467808 0.33528979 0.38049893]
 [0.13419528 0.39944709 0.16626536]]

Points B
[[0.8278716  1.29178416 0.50121951]
 [1.14340703 0.24961656 0.77973903]
 [0.8091441  0.89846046 0.23647586]
 [0.86981255 0.37375512 0.92081011]
 [0.97421239 1.14753075 0.56349385]
 [0.71662497 0.3777243  0.54892179]]

Ground truth rotation
[[ 0.42875487  0.87468101 -0.22605838]
 [ 0.89888101 -0.38797527  0.20368634]
 [-0.09045551  0.2905311   0.95258043]]
Recovered rotation
[[ 0.42875487  0.87468101 -0.22605838]
 [ 0.89888101 -0.38797527  0.20368634]
 [-0.09045551  0.2905311   0.95258043]]

Ground truth translation
[[0.31507231 0.36701658 0.33951471]]
Recovered translation
[[0.31507231 0.36701658 0.33951471]]

RMSE: 3.4313046682985327e-16


In [4]:
import numpy as np
 
def kabsch(A, B):
    """B is aligned to A"""
    assert A.shape == B.shape
 
    num_rows, num_cols = A.shape
    
    # find mean column wise
    centroid_A = np.mean(A, axis=1)
    centroid_B = np.mean(B, axis=1)
 
    # ensure centroids are 3x1
    centroid_A = centroid_A.reshape(-1, 1)
    centroid_B = centroid_B.reshape(-1, 1)
 
    # subtract mean
    Am = A - centroid_A
    Bm = B - centroid_B
   # # Calculate Familiar covariance matrix
    H = Am @ np.transpose(Bm)   # np.matmul(A,B.T)
 
    # find rotation...Using svd() operator which decomposes H 
    U, S, Vt = np.linalg.svd(H)
    R = Vt.T @ U.T
   #Trnslation
    t = -R @ centroid_A + centroid_B
 
    return R, t
 
#Example
#Robot
A = np.array([[800.559, -430.056,   339.981],
              [800.559,430.056, 339.923],
              [800.568,-430.041,    339.984],
              [610.023, -499.991,   340.058],
              [608.381, -498.282,   738.768],
              [800.559, 430.056,    339.98]])
 
A =A.T
#Camera
B = np.array([[386.523, -349.12,    2086.989],
              [-450.87, -284.62,    2031.087],
              [387.243, -351.53,    2087.195],
              [444.063, -343.04,    2276.608],
              [436.074,  45.092,    2291.748],
              [-453.0,  -292.26,    2031.054]])
B=B.T
 
 
 
 
#Function call:
R, t = kabsch(B, A)   # Swapped inorder to get the Tsystem inverse
 
#print("Rotation:",R.T)
#print("Tranlation:",t.T)
 
B = np.array([-103.976, -106.534,  2072.977,1])
 
B_1 = np.array([[-450.87, -284.62,    2031.087,1]])
print("")
# Tranformation matrix 
transform_cr= np.concatenate((R,t), axis =1)
scalingMatrix = np.array([[0,0,0,1]])
transform_cr = np.concatenate((transform_cr,scalingMatrix),axis = 0)
 
new = np.dot(transform_cr,B.T)
new_2 = np.dot(transform_cr,B_1.T)
print("Transformation matrix to be used for evalualtion:")
#print(transform_cr)
print(new)
 
print(new_2)


Transformation matrix to be used for evalualtion:
[783.96641434  74.82338086 548.28024343   1.        ]
[[797.60398621]
 [413.19250611]
 [350.47934746]
 [  1.        ]]


####Upload the corresponding robot log and sensor log in your colab/Jyputer notebook before running the application. 
#### Avoid using pycharm or other ide for plotly.
#### 'plot_in_RCS' function uses the transformation computed from kabsch function.

If any suggestions to modify the code please ping.

In [5]:
import pandas as pd
import plotly.express as px
import numpy as np
from scipy.signal import lfilter

In [8]:

def plot_in_RCS(robot_log_fname,sensor_log_fname, transformation_matrix_camera_to_rcs, noise = False):
  new = []
  df = pd.read_csv(sensor_log_fname, skiprows=6,usecols=["X.1", "Y.1", "Z.1"]).dropna()
  sensor_cartesian_array = np.array([df["X.1"].array.to_numpy(), df["Y.1"].array.to_numpy(), df["Z.1"].array.to_numpy()])
  for a in sensor_cartesian_array.transpose():
      a = np.append(a, 1)
      new.append(np.dot(transformation_matrix_camera_to_rcs, a.T))
  ufo = pd.DataFrame(new, columns=['X', 'Y', 'Z', 'Scaling'])
  ufo['CS'] = 'sensor_in_RCS'
  fig = px.line_3d(ufo,x='X', y='Y', z='Z',labels='sensor',color='CS')
  my_robot = pd.read_csv(robot_log_fname)  
  my_robot['CS']='Robot(RCS)'
  fig.add_traces(px.line_3d(my_robot,x='X',y='Y',z='Z',color='CS',color_discrete_sequence=['indianred']).data)
  fig.show()

In [12]:
plot_in_RCS('Recording_sensor_registration.csv','version_reg_2.csv',transform_cr)
plot_in_RCS('Recording_Arm_Angle_Test_3.csv','arm_angle_3.csv',transform_cr)

In [ ]:
plot_in_RCS('Recording_Backlash_Test_1.csv','backlash_1.csv',transform_cr)
plot_in_RCS('Recording_Arm_Angle_Test_1.csv','arm_angle_1.csv',transform_cr)
plot_in_RCS('Recording_Cartesian_Test_5.csv','cartesian_5.csv',transform_cr)
plot_in_RCS('Recording_Joint_Limit_4.csv','joint_4.csv',transform_cr)